"""
cleanroom.agents.verification
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
LangGraph node for the verification agent (spec §6).

The verification agent independently certifies that implementation agent
output satisfies all behavioral specifications.  It is the only entity that
may issue verification certificates — the implementation agent explicitly
CANNOT self-certify (spec §5.4).

The verification agent does NOT require an LLM for its core function: running
deterministic behavioral test cases against the implementation.  An LLM is
optional for auditing the decision log (spec §11.1).

Verification process per module (spec §6.2):
  1. Load behavioral test cases from spec store.
  2. Load property specifications from spec store.
  3. Execute all behavioral test cases against the implementation.
  4. Run property checker (invariant verification).
  5. Check spec coverage: every spec requirement has a test.
  6. Review decision log: every implementation choice has a spec reference.
  7. If all pass: issue verification certificate.
  8. If any fail: return rejection with the specific spec reference that failed.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from cleanroom.state import (
    CleanRoomState,
    SpecDocumentType,
    VerificationCertificate,
    make_audit_entry,
)


def build_verification_agent_node(spec_store: Any, audit_logger: Any):
    """
    Factory that returns a LangGraph node for the verification agent.

    Parameters
    ----------
    spec_store:
        Read-only access to behavioral test cases and property specs.
    audit_logger:
        Used to record verification outcomes as pipeline health signals.

    Returns
    -------
    Callable[[CleanRoomState], dict]
        A LangGraph node function.
    """

    def verification_agent_node(state: CleanRoomState) -> dict[str, Any]:
        """
        Run all verification steps for the current module.

        On success, issues a VerificationCertificate and adds the module to
        ``completed_modules``.  On failure, returns the state unchanged with
        an error message for the implementation agent to act on.
        """
        current_module = state.get("current_module")
        if not current_module:
            return {"error": "verification_agent called with no current_module"}

        # Step 1 & 2: Load test cases and property specs from spec store.
        test_cases = _load_test_cases(spec_store, current_module)
        property_specs = _load_property_specs(spec_store, current_module)

        # Step 3: Execute behavioral test cases.
        test_results = _run_behavioral_tests(test_cases, current_module)

        # Step 4: Verify properties / invariants.
        property_results = _verify_properties(property_specs, current_module)

        # Step 5: Check spec coverage.
        coverage_result = _check_spec_coverage(test_cases, current_module)

        # Step 6: Audit decision log.
        decision_log_complete = _check_decision_log(state, current_module)

        # Step 7 / 8: Issue certificate or rejection.
        all_passed = (
            test_results["failed"] == 0
            and property_results["all_passed"]
            and coverage_result["complete"]
            and decision_log_complete
        )

        if all_passed:
            cert = _issue_certificate(
                module=current_module,
                tests_passed=test_results["passed"],
                tests_failed=test_results["failed"],
                properties_verified=property_results["verified"],
                coverage=coverage_result["percentage"],
                decision_log_complete=decision_log_complete,
            )

            # Persist the certificate to the spec store.
            # The certificate is a spec store document (spec §7.2).
            # We use a synthetic approved guard decision ID here because
            # certificates are generated by verification, not by the analysis team.
            _store_certificate(spec_store, cert, current_module)

            audit_entry = make_audit_entry(
                event_type="cert_issued",
                agent_id="verification_agent",
                details={
                    "module": current_module,
                    "certificate_id": cert["certificate_id"],
                    "certified": True,
                    "tests_passed": cert["behavioral_tests_passed"],
                },
            )

            return {
                "completed_modules": [
                    *state.get("completed_modules", []),
                    current_module,
                ],
                "audit_log": [*state.get("audit_log", []), audit_entry],
                "error": None,
            }

        else:
            # Build a rejection message with the specific failing spec references.
            rejection_reasons = _build_rejection_message(
                test_results, property_results, coverage_result, decision_log_complete
            )

            audit_entry = make_audit_entry(
                event_type="cert_issued",
                agent_id="verification_agent",
                details={
                    "module": current_module,
                    "certified": False,
                    "rejection_reasons": rejection_reasons,
                },
            )

            return {
                "error": f"Verification failed for '{current_module}': {rejection_reasons}",
                "audit_log": [*state.get("audit_log", []), audit_entry],
            }

    return verification_agent_node


def route_verification(state: CleanRoomState) -> str:
    """
    LangGraph conditional edge: route based on verification outcome.

    Returns
    -------
    str
        ``"certified"``       → END (module complete)
        ``"rejected"``        → implementation_agent (fix and resubmit)
    """
    if state.get("error"):
        return "rejected"

    current = state.get("current_module")
    if current in state.get("completed_modules", []):
        return "certified"

    return "rejected"


# ---------------------------------------------------------------------------
# Verification steps (deterministic — no LLM required)
# ---------------------------------------------------------------------------

def _load_test_cases(spec_store: Any, module: str) -> list[dict[str, Any]]:
    """Load all behavioral test cases for *module* from the spec store."""
    doc_ids = spec_store.list_documents(module=module)
    cases = []
    for doc_id in doc_ids:
        if "test_case" in doc_id:
            doc = spec_store.read(doc_id, requester_role="verification_agent")
            cases.extend(doc["content"].get("test_cases", []))
    return cases


def _load_property_specs(spec_store: Any, module: str) -> list[dict[str, Any]]:
    """Load all property specifications for *module* from the spec store."""
    doc_ids = spec_store.list_documents(module=module)
    specs = []
    for doc_id in doc_ids:
        if "property_spec" in doc_id:
            doc = spec_store.read(doc_id, requester_role="verification_agent")
            specs.extend(doc["content"].get("properties", []))
    return specs


def _run_behavioral_tests(
    test_cases: list[dict[str, Any]], module: str
) -> dict[str, Any]:
    """
    Execute behavioral test cases against the module implementation.

    TODO: Dynamically import the implementation module from the working
    directory and execute each test case in isolation with a timeout.
    Currently returns a stub result.

    Each test case has the form:
      { "function": str, "inputs": dict, "expected_output": Any,
        "expected_error": str | None, "derivation": str }
    """
    # TODO: implement dynamic test execution
    # - Import implementation module by name
    # - For each test_case, call the function with test_case["inputs"]
    # - Compare result to test_case["expected_output"]
    # - Catch exceptions and compare to test_case["expected_error"]
    return {
        "passed": len(test_cases),  # stub: assume all pass
        "failed": 0,
        "failures": [],
    }


def _verify_properties(
    property_specs: list[dict[str, Any]], module: str
) -> dict[str, Any]:
    """
    Run invariant checks against the implementation.

    TODO: Each property spec includes a "falsification_scenario" that describes
    how to test the invariant.  Execute those scenarios and check the results.

    Returns a dict with:
      all_passed: bool
      verified: list[str] — names of verified properties
      failures: list[str] — names of failed properties
    """
    # TODO: implement property checking
    verified = [p.get("name", "unknown") for p in property_specs]
    return {
        "all_passed": True,
        "verified": verified,
        "failures": [],
    }


def _check_spec_coverage(
    test_cases: list[dict[str, Any]], module: str
) -> dict[str, Any]:
    """
    Verify that every spec requirement has at least one corresponding test case.

    TODO: Cross-reference the behavioral spec requirements against the test
    cases and return the coverage percentage.
    """
    # TODO: implement coverage check
    return {
        "complete": True,
        "percentage": "100%",
        "uncovered_requirements": [],
    }


def _check_decision_log(state: CleanRoomState, module: str) -> bool:
    """
    Verify that every significant implementation decision has a spec reference.

    TODO: Read the decision log from the implementation working directory and
    validate that each entry has a non-empty ``spec_ref`` field pointing to a
    real spec document ID.
    """
    # TODO: implement decision log validation
    return True


def _issue_certificate(
    module: str,
    tests_passed: int,
    tests_failed: int,
    properties_verified: list[str],
    coverage: str,
    decision_log_complete: bool,
) -> VerificationCertificate:
    """Construct a signed verification certificate."""
    return VerificationCertificate(
        certificate_id=str(uuid.uuid4()),
        module=module,
        timestamp=datetime.now(timezone.utc).isoformat(),
        behavioral_tests_passed=tests_passed,
        behavioral_tests_failed=tests_failed,
        properties_verified=properties_verified,
        spec_coverage=coverage,
        decision_log_complete=decision_log_complete,
        certified=True,
    )


def _store_certificate(
    spec_store: Any, cert: VerificationCertificate, module: str
) -> None:
    """
    Persist a verification certificate to the spec store.

    Certificates bypass the normal guard workflow because they originate from
    the verification agent, not from cross-zone communication.  We use a
    synthetic guard decision ID to satisfy the spec store's write requirement.

    TODO: Issue a proper "verification approved" event instead of a synthetic ID.
    """
    import uuid as _uuid
    from cleanroom.state import GuardClassification, make_guard_decision

    # Create a synthetic approved guard decision for the certificate write.
    synthetic_decision = make_guard_decision(
        direction="response",
        submitter="verification_agent",
        classification=GuardClassification.APPROVED,
        reason="Verification certificate — no cross-zone content.",
    )
    spec_store.store_guard_decision(synthetic_decision)

    spec_store.write(
        doc_type=SpecDocumentType.VERIFICATION_CERTIFICATE,
        module=module,
        content=dict(cert),
        guard_decision_id=synthetic_decision["request_id"],
        requester_role="verification_agent",
    )


def _build_rejection_message(
    test_results: dict[str, Any],
    property_results: dict[str, Any],
    coverage_result: dict[str, Any],
    decision_log_complete: bool,
) -> str:
    """Summarise all failure reasons into a single rejection string."""
    reasons = []
    if test_results["failed"] > 0:
        reasons.append(
            f"{test_results['failed']} behavioral test(s) failed: "
            f"{[f['test_id'] for f in test_results.get('failures', [])]}"
        )
    if not property_results["all_passed"]:
        reasons.append(f"Properties failed: {property_results['failures']}")
    if not coverage_result["complete"]:
        reasons.append(
            f"Spec coverage incomplete. Uncovered: {coverage_result['uncovered_requirements']}"
        )
    if not decision_log_complete:
        reasons.append("Decision log has entries without spec references.")
    return "; ".join(reasons) if reasons else "Unknown failure"
